import Head from "next/head";
import { Profile } from "@/containers/Profile";
import { Services } from "@/containers/Services";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cristian Esquivel Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <Profile />
        <Services />
      </main>
    </>
  );
}
